#!/bin/bash
#====================================================
# SCRIPT: ELH SERVER QUICK DEPLOY FOR X-UI
# DEVELOPED BY: netbro201031
# UPDATE DATE: 2021.11.06
# THIS REPO SPECIALLY MADE FOR ELH.NETWOXCLOUD SERVERS.
#====================================================

# Update System
sudo apt update 
# Upgrade System
sudo apt upgrade -y
# Install Firewalld
sudo apt-get install firewalld -y
# Open All Ports
firewall-cmd --zone=trusted --add-source=0.0.0.0/0
# Save Config
sudo firewall-cmd --runtime-to-permanent
# Reload Firewalld
sudo firewall-cmd --reload
# Adding Cron Jobs
(crontab -l && echo "#ELHX-UI") | crontab -
(crontab -l && echo "@reboot systemctl start firewalld") | crontab -
# Install Speedtest CLI
sudo apt install speedtest-cli
# Setup Time Zone
sudo timedatectl set-timezone Asia/Colombo
# Remove Junk Files
sudo apt autoremove -y
# Automate Removing Junk Files 
sudo sh -c 'echo "sudo apt autoremove -y" >> /etc/cron.monthly/autoremove'
# Setup Monthly Junk Remover Job
sudo chmod +x /etc/cron.monthly/autoremove
# System Update to install webmin
sudo apt update
clear
# Install SSL
sudo apt update
sudo apt install snapd
# Test your system
sudo snap install hello-world
hello-world
Sleep 10
clear
# Install lastes version of snapd
sudo snap install core; sudo snap refresh core
# Install Certbot
sudo snap install --classic certbot
# Prepare the Certbot command
sudo ln -s /snap/bin/certbot /usr/bin/certbot
# Install Bot
sudo apt-get install certbot -y
# End
echo "Part 01 Done !"
# Remove opcmake file
rm -r part1
